#!/bin/bash
SITE=`pwd`

echo "$SITE"
if [ $1 ]; then
    python $SITE/manage.py runserver $1 &
else
    python $SITE/manage.py runserver &
fi

stylus -w $SITE/static/css/style.styl -o $SITE/static/css/ &

echo " everything works like a charm! "
trap "kill -TERM -$$" SIGINT

wait